kind: Broker
apiVersion: eventing.knative.dev/v1
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: default-digital-wallet
  namespace: digital-wallet-dev
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: eda-demo-kafka-broker-config
    namespace: digital-wallet-dev